extends:
  - 'plugin:@ianwremmel/ianwremmel/node'
  - 'prettier'
  - 'prettier/@typescript-eslint'
  - 'plugin:import/typescript'

overrides:
  - files:
      - '**/*.spec.*'
      - 'test/jest/spec/**/*'
      - '**/__mocks__/**/*'
    env:
      jest: true
    rules:
      require-jsdoc: off
  - files:
      - '**/*.ts'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: './tsconfig.json'
      sourceType: 'module'

parserOptions:
  sourceType: 'script'

plugins:
  - '@typescript-eslint'
  - 'babel'
